# Generated by Django 3.1.3 on 2020-11-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_privilege'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_list',
        ),
        migrations.AddField(
            model_name='item',
            name='user_list',
            field=models.ManyToManyField(to='users.Profile'),
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
