# Generated by Django 3.1.3 on 2020-11-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20201116_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delta',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='expected_elapsed_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
