# Generated by Django 3.1.3 on 2020-11-15 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RD', 'READER'), ('ED', 'EDITOR'), ('OW', 'OWNER')], default='OW', max_length=2)),
                ('main_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
